version: 2.1
orbs:
  python: circleci/python@2.0.3

jobs:
  build_and_test_app:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run: pip install -r requirements.txt
      - run: 
          name: App Server
          command: python app.py
          background: true
      - run: python -m pytest tests/
      - persist_to_workspace:
          root: .
          paths:
            - 'tests'
      - attach_workspace:
          at: /tmp/workspace

  build_docker_image:
    docker: 
      - image: cimg/base:2024.02
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
          version: 20.10.24
        
      - run: docker build -t flask:latest .
      - run: docker run -d -p 5500:5500 flask:latest
      - run: python -m pytest tests/
      - persist_to_workspace:
          root: .
          paths:
            - 'tests'
      - attach_workspace:
          at: /tmp/workspace
workflows:
  build:
    jobs:
      - build_and_test_app
      - build_docker_image



                
