version: 2.1
orbs:
  python: circleci/python@2.0.3
  aws-ecr: circleci/aws-ecr@9.3.7

jobs:
  build_and_test_app:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run: pip install -r requirements.txt
      - run: 
          name: App Server
          command: python app.py
          background: true
        # run and save the tests
      - run:
          name: Create directory for tests
          command: mkdir results

      - run: python -m pytest tests/

      - persist_to_workspace:
          root: .
          paths:
            - 'tests'
    
      - store_test_results:
          path: results

  build_docker_image:
    docker: 
      - image: cimg/base:2024.02
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
          version: 20.10.24
        
      - run: docker build -t flask:latest .
      - run:
          name: Run Flask app in Docker container
          command: | 
            docker run -d --name flask -p 5500:5500 flask:latest
            docker stop flask
            docker rm flask

workflows:
  build_deploy:
    jobs:
      - build_and_test_app
      - build_docker_image:
          requires:
            - build_and_test_app



                
